
include: package:very_good_analysis/analysis_options.yaml

analyzer: 
  language:  
    strict-casts: true
    strict-raw-types: true

  exclude:  
    - lib/product/init/generation/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/build/**"
    - "test/.test_covarage.dart"
    - "test/"
    - "assets/translations/**"

  errors:  
    missing_return: error
    dead_code: error
    unused_import: info

linter:

  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_empty_else: true
    depend_on_referenced_packages: false
    public_member_api_docs: false
    sort_constructors_first: true
    prefer_const_constructors: true
    flutter_style_todos: false
    use_setters_to_change_properties: false
    one_member_abstracts: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    prefer_final_locals: true
    prefer_final_in_for_each: true 
    unnecessary_this: true
    avoid_unnecessary_containers: true
    use_super_parameters: true